ECELL_MAJOR_VERSION=3
ECELL_MINOR_VERSION=3
ECELL_MICRO_VERSION=alpha
ECELL_PACKAGE_REVISION=1
ECELL_VERSION_NUMBER=${ECELL_MAJOR_VERSION}.${ECELL_MINOR_VERSION}.${ECELL_MICRO_VERSION}${ECELL_PACKAGE_REVISION}
